# Generated by Django 3.0.5 on 2020-07-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(default='', max_length=200)),
                ('names', models.CharField(default='', max_length=200)),
                ('addresses', models.CharField(default='', max_length=200)),
                ('states', models.CharField(default='', max_length=70)),
                ('prices', models.IntegerField()),
                ('bedrooms', models.CharField(default='', max_length=5)),
                ('bathrooms', models.CharField(default='', max_length=5)),
                ('built_ups', models.IntegerField()),
                ('built_years', models.CharField(default='', max_length=10)),
                ('house_types', models.CharField(default='', max_length=70)),
                ('furnishings', models.CharField(default='', max_length=70)),
                ('prices_per_sqft', models.CharField(default='', max_length=10)),
                ('images', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
